name: "Expression des besoins d'interopérabilité"
description: >
  Utilisez ce formulaire pour exprimer vos besoins d'interopérabilité en santé.
  Remplissez toutes les sections obligatoires pour faciliter le traitement de votre demande.
labels: 
  - CI-SIS
  - Interopérabilité

body:
  - type: markdown
    attributes:
      value: |
        ## Note d’utilisation
        Merci de remplir toutes les sections obligatoires correspondant à votre demande de manière détaillée et si possible les sections indiquées comme optionnelles. Le formulaire rempli ainsi que les éventuelles pièces jointes sont à transmettre par courriel à l’adresse ci-sis@esante.gouv.fr.

  - type: input
    id: titre
    attributes:
      label: "Titre du besoin"
      description: "Le titre sera utilisé pour la publication sur le site esante.gouv.fr."
      placeholder: "Indiquez le titre ici"
    validations:
      required: true

  - type: checkboxes
    id: rubrique
    attributes:
      label: "Rubrique"
      options:
        - label: "Couche Métier"
        - label: "Couche Service"
        - label: "Couche Transport"
        - label: "Autre (préciser ci-dessous)"
    
  - type: textarea
    id: autre_rubrique
    attributes:
      label: "Autre Rubrique"
      description: "Si vous avez coché 'Autre', précisez ici."

  - type: input
    id: porteur_prenom_nom
    attributes:
      label: "Prénom et Nom du porteur de besoins"
      placeholder: "Indiquez le prénom et nom"

  - type: input
    id: porteur_organisation
    attributes:
      label: "Organisation du porteur de besoins"
      placeholder: "Indiquez l'organisation"

  - type: input
    id: porteur_email
    attributes:
      label: "Adresse de messagerie"
      placeholder: "Indiquez l'adresse e-mail"
      validation:
        required: true
        pattern: "^\\S+@\\S+\\.\\S+$"

  - type: textarea
    id: contexte_besoins
    attributes:
      label: "Contexte des besoins"
      description: "Décrivez le contexte dans lequel s’inscrivent vos besoins."

  - type: checkboxes
    id: impact_interet
    attributes:
      label: "Impact et intérêt"
      description: "Évaluez l'impact sur les systèmes et l'intérêt pour l'écosystème."
      options:
        - label: "Impact sur les systèmes (1 à 5)"
        - label: "Intérêt pour l'écosystème (1 à 5)"
        - label: "Complexité estimée (1 à 5)"
        - label: "Risque à ne pas faire (1 à 5)"
    
  - type: textarea
    id: commentaires
    attributes:
      label: "Commentaires supplémentaires"
      description: "Ajoutez tout autre élément pertinent pour votre demande."

