name: "(CI-SIS) Formulaire d’expression de besoins d’interopérabilité"
description: >
  Cible: tout acteur des domaines sanitaire, médico-social et médico-administratif identifiant des besoins d’interopérabilité entre au moins deux systèmes.
title: "[EBE]: "
labels: ["EBE"]
body:
  - type: markdown
    attributes:
      value: |
        ## Note d’utilisation du formulaire
        En préambule, merci de remplir les éléments obligatoires dans la partie “DESCRIPTION DE VOS BESOINS”    ainsi que les champs marqués optionnels (si possible).
        Ensuite :
        - Si votre demande concerne la création ou la modification de volets dans le partage des informations (standardisation du format)  Veuillez compléter la PARTIE SYN-TAXIQUE du formulaire (a minima les éléments obligatoires).

        - ET/OU si votre demande concerne la publication d’une Terminologie ou d’un ali-gnement (création ou hébergement)  Veuillez compléter la PARTIE SEMANTIQUE du formulaire (a minima les éléments obligatoires).

        - ET/OU si votre demande concerne la publication d’une ou plusieurs bibliothèques médicales (exemples CQL, AQL) (création ou hébergement)  Veuillez compléter la PARTIE CONNAISSANCES (a minima les éléments obligatoires).

        Le formulaire rempli, ainsi que les éventuelles pièces jointes sont à trans-mettre par courriel à l’adresse ci-sis@esante.gouv.fr

  - type: markdown
    attributes:
      value: |
        # DESCRIPTION DE VOS BESOINS

  - type: input
    id: titre
    attributes:
      label: "Titre du besoin"
      description: "Le titre sera utilisé pour la publication sur le site esante.gouv.fr."
      placeholder: "Indiquez le titre ici"
    validations:
      required: true
 
  - type: input
    id: Nom_prenom
    attributes:
      label: Prénom et Nom du demandeur
      description: Prénom et Nom
    validations:
      required: true
  - type: input
    id: organisation
    attributes:
      label: Organisation du demandeur
      description: A quelle organisation êtes-vous ratacchée ?   
    validations:
      required: true
  - type: input
    id: mail
    attributes:
      label: Adresse mail
      description: Renseignez votre adresse mail
    validations:
      required: true  
 

  - type: textarea
    id: sponsors
    attributes:
      label: "Sponsors"
      description: "Liste des sponsors soutenant l'expression de besoin (Organisation, Nom, Prénom et mail)."
      validations:
        required: true 

  - type: textarea
    id: parties_prenantes
    attributes:
      label: "Parties Prenantes"
      description: "Merci de nous indiquer si d'autres acteurs sont aussi impliqués dans l'expression de ces besoins (Organisation, Nom, Prénom et mail)"

  - type: markdown
    attributes:
      value: |
        ### Contexte des besoins 

  - type: dropdown
    id: contexte_projet_programme
    attributes:
      label: "Les besoins s’inscrivent-ils dans un projet ou programme national/international ?"
      options:
        - "Oui (précisez ci-dessous)"
        - "Non (justifiez ci-dessous)"
    validations:
      required: true
  
  - type : textarea
    id: precision_contexte
    attributes:
      label : "Précisez dans le cadre de quel projet ou programme national/international. Le cas échéant décrire ici le cadre réglementaire qui justifie votre demande (références vers les décrets)"
    validations:
      required: true

  - type: textarea
    id: oui_contexte_programme
    attributes:
      label: "Projet ou programme national/international"
      description: "Précisez dans le cadre de quel projet ou programme national/international"
    validations:
      required: true
    condition :
      if: contexte_projet_programme
      is: "Oui (justifiez ci-dessous)"

  - type: textarea
    id: non_contexte_programme
    attributes:
      label: "Cadre réglementaire"
      description: "Le cas échéant décrire ici le cadre réglementaire qui justifie votre demande (références vers les décrets)"
    validations:
      required: true
    condition :
      if: contexte_projet_programme
      is: "Non (justifiez ci-dessous)"

  - type: checkboxes
    id: complement_expression
    attributes:
      label: "Les besoins sont-ils un complément d’une expression ou travaux en cours ?"
      options:
        - label: "Oui (préciser les titres des besoins concernés)"
        - label: "Non"
      validations:
        required: true
  
  - type: textarea
    id: travaux
    attributes:
      label: "Travaux en cours"
      description: "Si oui, précisez ici les titres des besoins concernés si vous avez répondu oui à la question précédente."
    validations:
      required: true
    condition:
      if: complement_expression
      is: "Oui (préciser les titres des besoins concernés)"


  - type: textarea
    id: references
    attributes:
      label: "Références"
      description: "Ajouter toutes les références (articles, décrets) justifiant votre demande."

  - type: textarea
    id: synthese_besoins
    attributes:
      label: "Synthèse des besoins exprimés"
      description: "Cette synthèse sera utilisée pour la publication des besoins sur le site esante.gouv.fr."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Impact et intérêt (risques et bénéfices) 

  - type: dropdown
    id: impact_systeme
    attributes:
      label: "Impact sur les systèmes"
      description: "Estimation de l'impact sur les systèmes (1 = faible à 5 = fort)."
      options:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    validations:
      required: true

  - type: dropdown
    id: interet_ecosysteme
    attributes:
      label: "Intérêt pour l'écosystème"
      description: "Estimation de l'intérêt pour l'écosystème (1 = faible à 5 = fort)."
      options:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    validations:
      required: true

  - type: dropdown
    id: estimation_complexite
    attributes:
      label: "Estimation de la complexité"
      description: "Estimation de la complexité de la demande (1 = faible à 5 = fort)."
      options:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    validation:
      required: true

  - type: dropdown
    id: risque_non_faire
    attributes:
      label: "Risque à ne pas faire"
      description: "Estimation du risque associé à ne pas traiter cette demande (1 = faible à 5 = fort)."
      options:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    validation:
      required: true

  - type: textarea
    id: risques_identifies
    attributes:
      label: "Décrivez et justifiez les risques identifiés."
    validation:
      required: true

  - type: textarea
    id: benefices_attendus
    attributes:
      label: "Décrivez et justifiez les bénéfices attendus."
    validation:
      required: true
    
  - type: textarea
    id: delai_contraintes
    attributes:
      label: "Délai et contraintes projet"
      description: "Indiquer ici si vous avez des contraintes de délai à prendre en compte pour le traitement de votre demande (jalons projet, contraintes réglementaires etc)."

  - type: markdown
    attributes:
      value: |
        ## PARTIE SYNTAXIQUE (SPECIFIQUE)
        Cette section sert à donner une vue globale du périmètre des besoins. 

  - type: textarea
    id: cas_usage_syntaxique
    attributes:
      label: "Cas d’usage (Partie Syntaxique)"
      description: |
        "Décrire le(s) cas d’usage métier dans le(s)quel(s) s’inscrivent vos besoins, en particulier :
          - les transmissions de contenu à effectuer de manière dématérialisée (i.e. en utilisant un composant informatique), en explicitant quel acteur humain (ex. professionnel de santé) produit le contenu et quels acteurs (utilisant un autre composant informatique) en sont les destinataires ou sont intéressés à le consulter ultérieurement ;
          - les actions réalisées via un composant informatique sur un autre composant informatique.
          Le(s) cas d'usage peut/peuvent être présenté(s) sous la forme d'une petite histoire qui, si possible, indique quand un élément informatique est utilisé. Ces éléments seront utilisés pour l’élaboration des échanges fonctionnels.

          Attention : L’objectif est de faire émerger les besoins d’interopérabilité entre composants informatiques. Si au cours de la description du cas d’usage, il apparait évident que les transmissions de contenu décrites ou les actions réalisées le sont toujours au sein du même composant ou du même logiciel, il est probable que le besoin exprimé ne soit pas un besoin d’interopérabilité mais un besoin d’évolution d’un logiciel en particulier."
    validations:
      required: true

  - type: textarea
    id: problematique_syntaxique
    attributes:
      label: "Problématique (Partie Syntaxique)"
      description: "À partir du scénario d’usage, expliquer la problématique rencontrée en termes d’interopérabilité."
    validations:
      required: true

  - type: Markdown
    id: description_echange 
    attributes:
      value: |
        "À partir du/des cas d’usage métier décrit(s) en section 1, dégager les différents modules du Système d’Information intervenant dans les échanges. 
        Exemples : Module « créateur de documents médicaux », Module « Administration Patient », etc.  Décrire le rôle de chaque module et ses interactions avec les autres modules. Si connus, donner des éléments quantitatifs : indications de volumes, de répartition géographique, de fréquence, etc."

  - type: input
    id: Module_source
    attributes:
      label: "Description des échanges entre systèmes: Module source"
      description : Module source
    validations:
      required: true

  - type: input
    id: Module_destinataire
    attributes:
      label: "Description des échanges entre systèmes: Module destinataire"
      description : Module destinataire
    validations:
      required: true

  - type: input
    id: Objectif_general
    attributes:
      label: "Description des échanges entre systèmes: Objectif général"
      description : Objectif général
    validations:
      required: true

  - type: input
    id: Donnees_transmises
    attributes:
      label: "Description des échanges entre systèmes: Principales données transmises"
      description : Principales données transmises
    validations:
      required: true

  - type: input
    id: Evènement_declencheur
    attributes:
      label: "Description des échanges entre systèmes: Prérequis et évènement(s) déclencheur(s)"
      description : Prérequis et évènement(s) déclencheur(s)
    validations:
      required: true

  - type: input
    id: Actions_declenchees
    attributes:
      label: "Description des échanges entre systèmes: Actions déclenchées"
      description : Actions déclenchées
    validations:
      required: true


  - type: checkboxes
    id: jeux_valeurs
    attributes:
      label: "Besoin de jeux de valeurs ou spécificités sémantiques en complément de la demande ?"
      options:
        - label: "Oui"
        - label: "Non"

  - type: markdown
    id: jdv
    attributes:
      value: |
        "Si vous avez exprimé un besoin de jeux de valeurs, veuillez remplir la partie sémantique suivante"
        
  - type: textarea
    id: jeux_valeurs_details
    attributes:
      label: "Compléments"
      description: "Complétez ici si vous avez répondu oui à la question précédente."

  - type: markdown
    attributes:
      value: |
        ## PARTIE SEMANTIQUE (SPECIFIQUE)

  - type: textarea
    id: cas_usage_semantique
    attributes:
      label: "Cas d’usage (Partie Sémantique)"
      description: |
        Décrire le(s) cas d’usage métier dans le(s)quel(s) s’inscrivent vos besoins en détaillant comment est utilisée actuellement et/ou sera utilisée la Terminologie.
        Le(s) cas d'usage peut/peuvent être présenté(s) sous la forme d'une petite histoire, si possible en fonction des thématiques suivantes 

  - type: textarea
    id: problematique_semantique
    attributes:
      label: "Problématique (Partie Sémantique)"
      description: "À partir du scénario d’usage, expliquer la problématique rencontrée en termes d’interopérabilité que cette demande solutionnerait. Décrire :
                    - la situation actuelle et la situation cible. 
                    - le besoin en ressources sémantique (domaine de connaissance cible, terminologie vs jeux de valeurs, alignements)" 


  - type: markdown
    attributes:
      value: |
        ### Prérequis à la publication et travaux associés 

  - type: input
    id: format_actuel
    attributes:
      label: "Quel est le format actuel de votre (vos) Terminologie(s) ?"
      description: |
        Décrire le format actuel de votre Terminologie, la volumétrie, les interactions avec d’autres terminologies, le niveau de maturité, et la langue utilisée (exemple : Excel, PDF, Access, etc.) 

  - type: input
    id: volumetrie
    attributes:
      label: "Avez-vous une estimation de la volumétrie du contenu de votre Terminologie (nombre de codes)"

  - type: dropdown
    id: maturite_semantique
    attributes:
      label: "Quel est le niveau de maturité de la structure de votre Terminologie "
      description: "1 = faible à 5 = fort"
      options:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"

  - type: textarea
    id: interaction_multiterminologie
    attributes:
      label: "Votre Terminologie a-t-elle des interactions/liens avec d’autres Terminologies ?"

  - type: checkboxes
    id: multilingue
    attributes:
      label: "Votre Terminologie est-elle multilangue ?"
      options:
        - label: "Oui (préciser la langue ci-dessous)"
        - label: "Non"

  - type: textarea
    id: langue
    attributes:
      label: "Langue"
      description: |
        Si votre Terminologie est multilingue merci de préciser la langue.

  - type: checkboxes
    id: implication_ans
    attributes:
      label: "Quel est votre niveau d’attente sur le niveau d'implication de l'ANS ?"
      options:
        - label: "Assistance à maîtrise d’ouvrage et à la diffusion de votre Terminologie"
        - label: "Autres attentes"

  - type: textarea
    id: precision_implication
    attributes:
      label: "Si vous avez répondu 'Autres attentes', pouvez vous préciser les attentes que vous avez vis à vis de l'ANS ?"


  - type: textarea
    id: unite_production
    attributes:
      label: "Avez-vous identifié l’Unité de Production de votre Terminologie ?"
      description: |
        L’Unité de Production de Terminologies (UP) assure une activité de gestion (production, maintenance, diffusion, formation) d’une Terminologie selon des modalités documentées et sécurisées

  - type : input 
    id: orga_respo
    attributes:
      label : "Quel est l’organisme responsable de la production de la Terminologie ? "

  - type: textarea
    id: equipe_projet
    attributes:
      label: "Comment se compose l’équipe en charge du projet de la Terminologie ? "
      description: |
        Exemple : existence d’une équipe système d’information en appui du chef de projet

  - type: textarea
    id: politique_gestion_termino
    attributes:
      label: "Possédez-vous une politique de gestion de votre Terminologie ?"
      description: |
        La politique de gestion est un document spécifiant les modalités de gestion d’une Terminologie par l’Unité de production


  - type: input
    id: frequence_evolution
    attributes:
      label: "A quelle fréquence envisagez-vous l’évolution de votre Terminologie ? "
      description: "exemple : men-suelle, annuelle, etc."

  - type: textarea
    id: propriete_intellectuelle
    attributes:
      label: "Propriété intellectuelle"
      description: |
        En cas d'utilisation d’une licence autre que LOV2, expliquer les modalités d’accès à la Terminologie (ex: traçabilité des utilisateurs avec un mode connecté).

  - type : markdown
    id: def_lov2
    attributes :
      value: |
        "LOV2 : Licence ouverte figurant sur la liste, prévue par la loi pour une République numérique et fixée par dé-cret, de licences pouvant être utilisées par les administrations pour la réutilisation des informations pu-bliques (https://www.data.gouv.fr/fr/pages/legal/licences/)."


  - type: textarea
    id: utilisateurs_terminologie
    attributes:
      label: "Quels sont les utilisateurs de votre Terminologie ? "
      description: "Décrire l’audience visée par votre Terminologie."

  - type: markdown
    attributes:
      value: |
        ## ELEMENTS COMPLEMENTAIRES
        Cette section sert à donner une vue globale du périmètre des besoins. Décrire le(s) cas d’usage métier dans le(s)quel(s) s’inscrivent vos besoins, en particulier :
        - Si le besoin concerne la standardisation d’un Guide de Bonnes Pratiques Cliniques (GBPC).
        - Si le besoin concerne le développement d’une bibliothèque CQL dans le cadre d’un cas d’usage syntaxique
        Si le besoin concerne le déploiement de bibliothèques CQL sous forme de Système d’Aide à la Décision Clinique (SADC) avec le standard CDS Hooks Dans tous les cas, le cas d’usage métier doit-être décrit avec des diagrammes de cas d’utilisation UML agrémentés d’autres diagrammes UML et/ou description textuel du cas d’usage. La description UML doit pouvoir préciser au minimum : les acteurs, les flux entre les acteurs, les composants logiciels. Pour cela, suivez la méthode d’élaboration des échanges fonctionnels (méthode disponible sur notre site).


  - type: textarea
    id: cas_usage_connaissance
    attributes:
      label: "Cas d'usage (Partie Connaissance)"
      description: "Décrire votre cas d'usage"

  - type: checkboxes
    id: besoin_syntaxique
    attributes:
      label: "Avez-vous des besoins syntaxiques en lien avec le cas d'usage ?"
      options:
        - label: "Oui (la partie syntaxique doit être complétée)"
        - label: "Non"

  - type: checkboxes
    id: besoin_semantique
    attributes:
      label: "Avez-vous des besoins sémantiques en lien avec le cas d'usage ?"
      options:
        - label: "Oui (la partie sémantique doit avoir été remplie)"
        - label: "Non"