name: "(CI-SIS) Expression de besoins d’interopérabilité"
description: >
  Cible: tout acteur des domaines sanitaire, médico-social et médico-administratif identifiant des besoins d’interopérabilité entre au moins deux systèmes.
title: "[EBE]: "
labels: ["EBE"]
body:
  - type: markdown
    attributes:
      value: |
        ## Note d’utilisation
        Pour nous soumettre votre demande il vous faut:
         
        * télécharger le document à compléter [ici](https://interop.esante.gouv.fr/ig/doctrine/CI-SIS_FORMULAIRE_EXPRESSION%20DE%20BESOINS.docx)
        Une fois le document complété, veuillez l'enregistrer au format pdf.
        * Avoir un compte github [(documentation pour créer un compte)](https://docs.github.com/fr/get-started/start-your-journey/creating-an-account-on-github)
  - type: textarea
    id: form
    attributes:
      label: "Formulaire complété"
      description: "Veuillez joindre ici votre formulaire de demande complété. A noter que ce docuement sera visible publiquement"
      
  - type: markdown
    attributes:
      value: |
        ## Processus de traitement de votre demande 
        Le porcessus de traitement de votre demande est décrit dans la [Gouvernance du CI-SIS](https://interop.esante.gouv.fr/ig/doctrine/ebe-cp.html#expressions-de-besoins-dint%C3%A9rop%C3%A9rabilit%C3%A9)
