name: "(CI-SIS) Formulaire d’expression de besoins d’interopérabilité"
description: >
  Cible: tout acteur des domaines sanitaire, médico-social et médico-administratif identifiant des besoins d’interopérabilité entre au moins deux systèmes.
title: "[EBE]: "
labels: ["EBE"]
body:
  - type: markdown
    attributes:
      value: |
        ## Note d’utilisation du formulaire
        En préambule, merci de remplir les éléments obligatoires dans la partie “DESCRIPTION DE VOS BESOINS”    ainsi que les champs marqués optionnels (si possible).
        Ensuite :
        •	Si votre demande concerne la création ou la modification de volets dans le partage des informations (standardisation du format)  Veuillez compléter la PARTIE SYN-TAXIQUE du formulaire (a minima les éléments obligatoires).

        •	ET/OU si votre demande concerne la publication d’une Terminologie ou d’un ali-gnement (création ou hébergement)  Veuillez compléter la PARTIE SEMANTIQUE du formulaire (a minima les éléments obligatoires).

        •	ET/OU si votre demande concerne la publication d’une ou plusieurs bibliothèques médicales (exemples CQL, AQL) (création ou hébergement)  Veuillez compléter la PARTIE CONNAISSANCES (a minima les éléments obligatoires).

        Le formulaire rempli, ainsi que les éventuelles pièces jointes sont à trans-mettre par courriel à l’adresse ci-sis@esante.gouv.fr

  - type: markdown
    attributes:
      value: |
        # DESCRIPTION DE VOS BESOINS

  - type: input
    id: titre
    attributes:
      label: "Titre du besoin"
      description: "Le titre sera utilisé pour la publication sur le site esante.gouv.fr."
      placeholder: "Indiquez le titre ici"
    validations:
      required: true
 
  - type: input
    id: Nom_prenom
    attributes:
      label: Prénom et Nom du demandeur
      description: Prénom et Nom
    validations:
      required: true
  - type: input
    id: organisation
    attributes:
      label: Organisation du demandeur
      description: A quelle organisation êtes-vous ratacchée ?   
    validations:
      required: true
  - type: input
    id: mail
    attributes:
      label: Adresse mail
      description: Renseignez votre adresse mail
    validations:
      required: true  
  - ##type: input
    #id: telephone
    #attributes:
     # label: Numéro de téléphone
    #  description: Renseignez votre adresse mail
    #validations:
    #  required: true  

  - type: textarea
    id: sponsors
    attributes:
      label: "Sponsors"
      description: "Liste des sponsors soutenant l'expression de besoin (Organisation, Nom, Prénom et mail)."
      validations:
        required: true 

  - type: textarea
    id: parties_prenantes
    attributes:
      label: "Parties Prenantes"
      description: "Merci de nous indiquer si d'autres acteurs sont aussi impliqués dans l'expression de ces besoins (Organisation, Nom, Prénom et mail)"

  - type: markdown
    attributes:
      value: |
        ### Contexte des besoins 

  - type: dropdown
    id: contexte_projet_programme
    attributes:
      label: "Les besoins s’inscrivent-ils dans un projet ou programme national/international ?"
      options:
        - "Oui (précisez ci-dessous)"
        - "Non (justifiez ci-dessous)"
    validations:
      required: true
  - type: textarea
    id: oui_contexte_programme
    attributes:
      label: "Projet ou programme national/international"
      description: "Précisez dans le cadre de quel projet ou programme national/international"
    validations:
      required: true
    condition :
      when: contexte_projet_programme
      is: "Oui (justifiez ci-dessous)"

  - type: textarea
    id: non_contexte_programme
    attributes:
      label: "Cadre réglementaire"
      description: "Le cas échéant décrire ici le cadre réglementaire qui justifie votre demande (références vers les décrets"
    validations:
      required: true
    condition :
      when: contexte_projet_programme
      is: "Non (justifiez ci-dessous)"

  - type: checkboxes
    id: complement_expression
    attributes:
      label: "Les besoins sont-ils un complément d’une expression ou travaux en cours ?"
      options:
        - label: "Oui (préciser les titres des besoins concernés)"
        - label: "Non"
      validations:
        required: true
  
  - type: textarea
    id: travaux
    attributes:
      label: "Travaux en cours"
      description: "Précisez ici les titres des besoins concernés si vous avez répondu oui à la question précédente."
    validations:
      required: true
    condition:
      when: complement_expression
      is: "Oui (préciser les titres des besoins concernés)"


  - type: textarea
    id: references
    attributes:
      label: "Références"
      description: "Ajouter toutes les références (articles, décrets) justifiant votre demande."

  - type: textarea
    id: synthese_besoins
    attributes:
      label: "Synthèse des besoins exprimés"
      description: "Cette synthèse sera utilisée pour la publication des besoins sur le site esante.gouv.fr."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Impact et intérêt (risques et bénéfices) 

  - type: dropdown
    id: impact_systeme
    attributes:
      label: "Impact sur les systèmes"
      description: "Évaluez l'impact sur les systèmes (1 = faible à 5 = fort)."
      options:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    validations:
      required: true

  - type: dropdown
    id: interet_ecosysteme
    attributes:
      label: "Intérêt pour l'écosystème"
      description: "Évaluez l'intérêt pour l'écosystème (1 = faible à 5 = fort)."
      options:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    validations:
      required: true

  - type: dropdown
    id: estimation_complexite
    attributes:
      label: "Estimation de la complexité"
      description: "Évaluez la complexité de la demande (1 = faible à 5 = fort)."
      options:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    validations:
      required: true

  - type: dropdown
    id: risque_non_faire
    attributes:
      label: "Risque à ne pas faire"
      description: "Évaluez le risque associé à ne pas traiter cette demande (1 = faible à 5 = fort)."
      options:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    validations:
      required: true

  - type: table
    id: risques_benefices_table
    attributes:
      label: "Décrivez et justifiez les risques et /ou les bénéfices attendus."
    columns:
      - header: "Type"
        id: type
        options:
          - "Risques"
          - "Bénéfices"
      - header: "Description"
        id: description
    validations:
      required: true
    
  - type: textarea
    id: delai_contraintes
    attributes:
      label: "Délai et contraintes projet"
      description: "Indiquer ici si vous avez des contraintes de délai à prendre en compte pour le traitement de votre demande (jalons projet, contraintes réglementaires etc)."

  - type: markdown
    attributes:
      value: |
        ## PARTIE SYNTAXIQUE (SPECIFIQUE)
        Cette section sert à donner une vue globale du périmètre des besoins. 

  - type: textarea
    id: cas_usage_syntaxique
    attributes:
      label: "Cas d’usage (Partie Syntaxique)"
      description: |
        "Décrire le(s) cas d’usage métier dans le(s)quel(s) s’inscrivent vos besoins, en particulier :
          •	les transmissions de contenu à effectuer de manière dématérialisée (i.e. en utilisant un composant informatique), en explicitant quel acteur humain (ex. professionnel de santé) produit le contenu et quels acteurs (utilisant un autre composant informatique) en sont les destinataires ou sont intéressés à le consulter ultérieurement ;
          •	les actions réalisées via un composant informatique sur un autre composant informatique.
          Le(s) cas d'usage peut/peuvent être présenté(s) sous la forme d'une petite histoire qui, si possible, indique quand un élément informatique est utilisé. Ces éléments seront utilisés pour l’élaboration des échanges fonctionnels.

          Attention : L’objectif est de faire émerger les besoins d’interopérabilité entre composants informatiques. Si au cours de la description du cas d’usage, il apparait évident que les transmissions de contenu décrites ou les actions réalisées le sont toujours au sein du même composant ou du même logiciel, il est probable que le besoin exprimé ne soit pas un besoin d’interopérabilité mais un besoin d’évolution d’un logiciel en particulier."

  - type: textarea
    id: problematique_syntaxique
    attributes:
      label: "Problématique (Partie Syntaxique)"
      description: "À partir du scénario d’usage, expliquer la problématique rencontrée en termes d’interopérabilité."

  - type: table
    id: description_echanges
    attributes:
      label: "Description des échanges entre systèmes"
    columns:
      - header: "Exemple de description d’échanges entre deux modules"
        id: type
        options:
          - "Module source"
          - "Module destinataire"
          - "Objectif général"
          - "Principales données transmises"
          - "Prérequis et évènement(s) déclencheur(s)"
          - "Actions déclenchées"
      - header: "Description"
        id: description
    validations:
      required: true
  - type: textarea
    id: 
    attributes:
      label: ""
      description: |
        "À partir du/des cas d’usage métier décrit(s) en section 1, dégager les différents modules du Système d’Information intervenant dans les échanges. 
        Exemples : Module « créateur de documents médicaux », Module « Administration Patient », etc.  Décrire le rôle de chaque module et ses interactions avec les autres modules. Si connus, donner des éléments quantitatifs : indications de volumes, de répartition géographique, de fréquence, etc."


  - type: checkboxes
    id: jeux_valeurs
    attributes:
      label: "Besoin de jeux de valeurs ou spécificités sémantiques en complément de la demande ?"
      options:
        - label: "Oui (préciser)"
        - label: "Non"
        
  - type: textarea
    id: jeux_valeurs_details
    attributes:
      label: "Compléments"
      description: "Complétez ici si vous avez répondu oui à la question précédente."

  - type: markdown
    attributes:
      value: |
        ## PARTIE SEMANTIQUE (SPECIFIQUE)

  - type: textarea
    id: cas_usage_semantique
    attributes:
      label: "Cas d’usage (Partie Sémantique)"
      description: |
        Décrire le(s) cas d’usage métier dans lesquels s’inscrivent vos besoins sémantiques, en expliquant comment la Terminologie est utilisée ou sera utilisée.

  - type: textarea
    id: problematique_semantique
    attributes:
      label: "Problématique (Partie Sémantique)"
      description: "Expliquer la problématique rencontrée en termes d’interopérabilité et comment cette demande y répondrait."

  - type: markdown
    attributes:
      value: |
        ### Prérequis à la publication et travaux associés 

  - type: textarea
    id: format_actuel
    attributes:
      label: "Format actuel"
      description: |
        Décrire le format actuel de votre Terminologie, la volumétrie, les interactions avec d’autres terminologies, le niveau de maturité, et la langue utilisée.

  - type: checkboxes
    id: multilingue
    attributes:
      label: "Votre Terminologie est-elle multilingue ?"
      options:
        - label: "Oui (préciser la langue ci-dessous)"
        - label: "Non"

  - type: textarea
    id: langue
    attributes:
      label: "Langue"
      description: |
        Si votre Terminologie est multilingue merci de préciser la langue.

  - type: textarea
    id: unite_production
    attributes:
      label: "Unité de Production"
      description: |
        Avez-vous identifié l’Unité de Production de votre Terminologie ? Précisez l’organisme responsable, la composition de l’équipe, et la politique de gestion.

  - type: textarea
    id: frequence_evolution
    attributes:
      label: "Fréquence d'évolution de la Terminologie"
      description: "Indiquer la fréquence d’évolution de votre Terminologie (ex : mensuelle, annuelle)."

  - type: textarea
    id: propriete_intellectuelle
    attributes:
      label: "Propriété intellectuelle"
      description: |
        En cas d'utilisation d’une licence autre que LOV2, expliquer les modalités d’accès à la Terminologie (ex: traçabilité des utilisateurs avec un mode connecté).

  - type: textarea
    id: utilisateurs_terminologie
    attributes:
      label: "Utilisateurs de la Terminologie"
      description: "Décrire l’audience visée par votre Terminologie."

  - type: markdown
    attributes:
      value: |
        ## ELEMENTS COMPLEMENTAIRES

  - type: textarea
    id: commplements
    attributes:
      label: "Commentaires et documents supplémentaires"
      description: "Ajoutez tout autre élément pertinent pour votre demande (commentaires et/ou tout document utile qui peut faciliter l’instruction de votre demande.)."

